// <auto-generated />
namespace PA2_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Actualizaciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Actualizaciones));
        
        string IMigrationMetadata.Id
        {
            get { return "202012110011320_Actualizaciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
